.\" Manpage for atb
.\" Contact us via Github to correct errors or typos : https://github.com/AdminToolsBox/ATB
.TH ATB 1 "03 Fevrier 2016" "2.1" "Page man de ATB"
.SH NAME
atb \- est un outîl pour administrateur système qui vous permet d'éxécuter des commandes complexes vraiment facilement sur un ordinateur distant.
.SH SYNOPSIS
atb [OPTION]
.SH DESCRIPTION

ATB est un outîl pour administrateur système qui vous permet d'éxécuter des commandes complexes vraiment facilement sur un ordinateur distant.
Ce programme est développé par des Etudiants de l'IUT d'Aubière 

.SH OPTIONS

.TP
\fB--help ou -h\fP 
Pour savoir quels scripts sont disponnibles et quelles commandes utiliser.

.TP
\fBalive\fP 
Permet de voir dans une plage d'adresses IP quelles sont les entitées en ligne (pingable).

.TP
\fBgit\fP 
Permet de configurer et d'utiliser Git plus rapidement et facilement. 

.TP
\fBinfosys\fP 
Permet d'obtenir des informations sur l'ordinateur distant.

.TP
\fBnmap\fP 
Menu simplifiant l'utilisation de la commande nmap. Requiert le paquet nmap. 

.TP
\fBtaskkill\fP 
Gestionnaire de tâches qui vous permet de voir les tâches principales qui sont en cours, d'en rechercher une en particulier et de la tuer.

.SH VOIR AUSSI
htop(1), nmap(A)

.SH BUGS
Pas de bugs connus.

.SH AUTEUR

.TP
\fbAlec Beaudroux (alecbx@yahoo.fr)\fp
.TP
\fbWilliam Misson (william@quarahtk.org)\fp

