.\" Manpage for atb
.\" Contact us via Github to correct errors or typos : https://github.com/AdminToolsBox/ATB
.TH ATB 1 "07 Janvier 2016" "2.0" "Page man de ATB"
.SH NAME
atb \- est un outil pour administrateur système qui vous permez d'éxécuter des commandes complexes vraiment facilement et sur un ordinateur distant.
.SH SYNOPSIS
atb [OPTION]
.SH DESCRIPTION

ATB est un outil pour administrateur systeme qui vous permez d'éxécuter des commandes complexes vraiment facilement et sur un ordinateur distant.
Ce programme est développé par des Etudiants de l'Université de Clermont Ferrand en France.  

.SH OPTIONS

.TP
\fB--help\fP 
Pour savoir quels scripts sont disponnible et quelles commandes utiliser.

.TP
\fBalive\fP 
Permet de voir dans une plage d'adresses IP qui sont les entitées en ligne (pingable).

.TP
\fBgit\fP 
Permet de configurer et d'utiliser Git. 

.TP
\fBinfosys\fP 
Permet d'obtenir des informations sur l'ordinateur distant.

.TP
\fBtaskkill\fP 
Gestionnaire de tâches qui vous permet de voir les tâches principales qui sont en cours, d'en rechercher une en particulié et de la tuer.

.SH VOIR AUSSI
htop(1), nmap(A)

.SH BUGS
Pas de bugs connus

.SH AUTEUR
William Misson (william@quarahtk.org)
