#!/bin/sh


user=$(whoami)
	case "$user" in  
  
		root)
			printf "Which language will be used in the manual ?\n" 
			printf "1 - English \n2 - French - Français\n"			
			read language 			
			case "$language" in
				1|en|english)			
					tar zcvf /usr/share/man/man1/atb.1.gz man/en/atb.1
					printf "The manual was install in English with sucess.\n"
					exit 0
				;;
				
				2|fr|french|français)
					tar zcvf /usr/share/man/man1/atb.1.gz man/fr/atb.1
					printf "Le manuel a bien été installé en Français.\n"
					exit 0
				;;

				*)			
					printf "The language specified isn't correct or available"	
					
				;;

				
			esac	
		;;
		*)	printf "This script need root permision, please run : "
			echo "\033[1;31;40m sudo $0 $* \033[0m"		
		
		;;

	esac




