#!/bin/sh


user=$(whoami)
	case "$user" in  
  
		root)

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "Man Page Instalation" \
    --title "Man Page" \
    --clear \
    --cancel-label "Exit" \
    --menu "Choose the man language :" $HEIGHT $WIDTH 4 \
    "English" "Man Page in English" \
    "French" "Page de Man en Français" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    0 )
      clear
      echo "Program terminated."
      ;;
	

English )
	tar zcvf /usr/share/man/man1/atb.1.gz man/en/atb.1	
	dialog \
    --backtitle "Instalation Complete" \
    --title "Instalation Complete" \
    --clear \
    --msgbox "Man Page was successfully instaled in English. \n 
You can access to it by tapping  : \n man atb" 7 60 \
      ;;

    French )
	tar zcvf /usr/share/man/man1/atb.1.gz man/fr/atb.1	
	dialog \
    --backtitle "Instalation Terminé" \
    --title "Instalation Terminé" \
    --clear \
    --msgbox "La page de Man en français a été installé avec succès. \n 
Vous pouvez accèder à cette page en tapant : \n man atb" 7 60 \
      ;;
  esac
done
		;;
		*)	
	
			dialog --title 'Root Permission Require ! ' --msgbox '\nThis script need root permision, please run : \n
			sudo ./maninstalldialog' 10 50
			clear		
		
		;;

	esac
