#!/bin/bash

## \file alxdr-lib
## \author William Le Pommelet
## \brief Library of fonctions for Admin Tools Box.
## \version 1.1.1
## \date November 27th 2014

## \cond DUMMY

source /usr/lib/ATB/i18n-lib

## \endcond

## \fn alxdr_checkInstalled
## \brief Check if the programm passed in argument is installed. If not, asks the user if he whants to install it.
## \param[in] 1 The name on the programm.
## \return 0 - The programm is installed, normal end.
## \return 1 - The user doesn't whant to install the programm.
## \return ? - The return value of "apt-get".
alxdr_checkInstalled()
{
	export TEXTDOMAIN=alxdr-lib
	eval $1
	if [ $? = "127" ]; then
		clear
		echo -e "$1\c" 
		i18n_error "notInstalled"
		read CHOIX
		if [ $CHOIX = "y" -o $CHOIX = "Y" -o $CHOIX = "o" -o $CHOIX = "O" ]; then
			sudo apt-get install $1 -y
			return $?
		else
			return 1
		fi
	else
		return 0
	fi
}
