#!/bin/bash

## \file i18n-lib
## \author Louis Iacona
## \brief Library for internationalization
## \date September 27th 2010
##
##  Thin library around basic I18N facilitated function basic text display, file logging, error display, and prompting.\n
## Soucres : http://www.linuxjournal.com/content/internationalizing-those-bash-scripts

## \cond DUMMY

export TEXTDOMAINDIR=/usr/locale/ATB

## \endcond

## \fn i18n_error 
## \brief Display some text to stderr.
## \param[in] 1 The Message Catalog key
i18n_error()
{
        echo "$(gettext -s "$1")" >&2
}

## \fn i18n_display
## \brief Display some text to sdtout.
## \param[in] 1 The Message Catalog key.
## \param[in] @ Misc information.
i18n_display()
{
        typeset key="$1"
        shift
        echo "$(gettext -s "$key") $@"
}

## \fn i18n_fileout
## \brief Append a log message to a file..
## \param[in] 1 Target file to append to.
## \param[in] 2 The Message Catalog key.
## \param[in] @ Misc information.
i18n_fileout()
{
        [[ $# -lt 2 ]] && return 1
        typeset file="$1"
        typeset key="$2"
        shift 2
        echo "$(gettext -s "$key") $@" >> ${file}
}


## \fn i18n_prompt
## \brief Prompt the user with a message and echo back the response.
## \param[in] 1 The Message Catalog key.
## \param[out] rv The response.
i18n_prompt()
{
        typeset rv
        [[ $# -lt 1 ]] && return 1
        read -p "$(gettext "$1"): " rv
        echo $rv
}
